# application.yml
# tomcat
server:
  port: 8080
  servlet:
    context-path: /spring
    session:
      timeout: 30m

# spring
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring
    password: spring
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      location: E:/Workspaces/spring_workspace/hello-springboot/src/main/webapp/resources/upload/board
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f961623a64519864569f6979c045f548
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}' #고정
            authorization-grant-type: authorization_code
            client-authentication-method: 'POST'
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: POST
            user-name-attribute: id
          
        

# logback
logging:
  level:
    root: info
    '[com.sh.app]': debug
    
# mybatis
mybatis:
  configuration: 
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  type-aliases-package: com.sh.app, org.springframework.security.core.authority
  type-handlers-package: com.sh.app.common.typehandler
  mapper-locations: classpath*:mapper/**/*-mapper.xml

#oauth
oauth:
  kakao:
    authorize-uri: https://kauth.kakao.com/oauth/authorize/
    redirect-uri: http://localhost:8080/spring/oauth/kakao/callback.do
    rest-api-key: f961623a64519864569f6979c045f548
    token-uri: https://kauth.kakao.com/oauth/token
    scope: profile_nickname, account_email, profile_image
    resource-uri-host: https://kapi.kakao.com
      